---
- name: Running the maven code
  hosts: localhost
  connection: local
  tasks:
    - name : Run the maven compile
      command: mvn clean compile
    - name: Run the maven install
      command: mvn clean package
    - name: Docker build
      docker_image:
        name: formycore/test:nov18
        build:
          path: .
        source: build
        state: present
